### ISSUE TITLE
自定义proto仓库，且依赖公共proto时代码生成失败

### ISSUE THREAD

**Issue by hxlhxl** [yunkeCN/grpc-code-gen#6]
- 版本
  "@types/protobufjs": "^6.0.0",
   "@yunke/grpc-resolve-path": "^1.0.5",
   "grpc-code-gen": "^6.0.0",
- 复现
   仓库： https://git.myscrm.cn/channel-core/bff-channel-core
   分支： f-20200426-12-channel-rule2
   命令： yarn grpc-gen -b f-20200426-12-channel-rule2
- 需求
  1. 支持自定义proto的grpc路径解析
  2. 解决自定义proto依赖公共proto时生成代码的bug。

**Comment by wangweianger** [comment]
升级到 6.1.0 版本即可
